### ISSUE TITLE
[Feature] Enable support for multiarch using single command

### ISSUE THREAD

**Issue by anmolnagpal** [clouddrove/enigma#26]

**Comment by nitishmalang** [comment]
@Bharadwajshivam28  I fixed it can I raise PR

**Comment by Bharadwajshivam28** [comment]
via Hubstaff
User: Shivam Kumar

Project: enigma - https://app.hubstaff.com/projects/3166954
Date Range: 10/04/24 - 10/04/24
Work session total: 4:06:21
Billable: Yes

Grand total: 4:06:21
